[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ava"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "PyGithub>=2.3.0",
    "loguru>=0.7.2",
    "schedule>=1.2.2",
]

[tool.pyright]
typeCheckingMode = "standard"
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
include = ["ava"]
extraPaths = ["."]
indexing = true
